# Generated by Django 5.2.5 on 2025-08-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.IntegerField()),
                ('end_ms', models.IntegerField()),
                ('speaker', models.CharField(blank=True, default='', max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.meeting')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
