# Generated by Django 5.2.5 on 2025-08-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('realtime', 'Realtime'), ('final', 'Final')], max_length=16)),
                ('raw_text', models.TextField()),
                ('keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_logs', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
