# Generated by Django 5.2.5 on 2025-08-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('market_area', models.CharField(blank=True, max_length=200, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('type', models.CharField(choices=[('heading', 'heading'), ('paragraph', 'paragraph'), ('list', 'list'), ('image', 'image'), ('table', 'table'), ('quote', 'quote'), ('code', 'code')], max_length=20)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('rich_payload', models.JSONField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('parent_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='meetings.block')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_block',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
                ('mime_type', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='meetings.block')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_attachment',
            },
        ),
        migrations.CreateModel(
            name='BlockRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('snapshot', models.JSONField()),
                ('edited_by', models.BigIntegerField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='meetings.block')),
            ],
            options={
                'db_table': 'meetings_block_revision',
                'indexes': [models.Index(fields=['block'], name='meetings_bl_block_i_311784_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['meeting'], name='meetings_bl_meeting_47c886_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['parent_block'], name='meetings_bl_parent__b4e1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['meeting'], name='meetings_at_meeting_082ffa_idx'),
        ),
    ]
