# Generated by Django 5.2.5 on 2025-08-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockrevision',
            options={'ordering': ('-edited_at', 'id')},
        ),
        migrations.RemoveField(
            model_name='block',
            name='version',
        ),
    ]
