# Generated by Django 5.2.5 on 2025-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingArea',
            fields=[
                ('trdar_cd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trdar_cd_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('trdar_se_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('trdar_se_cd_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('signgu_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('signgu_cd_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('adstrd_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('adstrd_cd_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_trading_area',
            },
        ),
        migrations.CreateModel(
            name='ChangeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trdar_cd', models.CharField(db_index=True, max_length=20)),
                ('yyq', models.CharField(db_index=True, max_length=7)),
                ('change_index', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'analytics_change_index',
                'unique_together': {('trdar_cd', 'yyq')},
            },
        ),
        migrations.CreateModel(
            name='ClosureStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('signgu_cd', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('signgu_cd_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('adstrd_cd', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('adstrd_cd_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
                ('closures', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_closure_stat',
                'indexes': [models.Index(fields=['year', 'signgu_cd'], name='analytics_c_year_ea744a_idx'), models.Index(fields=['year', 'adstrd_cd'], name='analytics_c_year_745dce_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndustryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trdar_cd', models.CharField(db_index=True, max_length=20)),
                ('yyq', models.CharField(db_index=True, max_length=7)),
                ('svc_induty_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('svc_induty_cd_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('thsmon_selng_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('thsmon_selng_co', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('mdwk_selng_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('wkend_selng_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'analytics_industry_metric',
                'unique_together': {('trdar_cd', 'yyq', 'svc_induty_cd')},
            },
        ),
    ]
