# Generated by Django 5.2.5 on 2025-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_changeindex_raw_data_closurestat_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeindex',
            name='change_level',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
