# Generated by Django 5.2.5 on 2025-08-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_changeindex_change_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyq', models.CharField(db_index=True, max_length=6)),
                ('trdar_cd', models.CharField(db_index=True, max_length=20)),
                ('trdar_cd_nm', models.CharField(max_length=100)),
                ('svc_induty_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('svc_induty_cd_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_amt', models.BigIntegerField(blank=True, null=True)),
                ('sales_cnt', models.BigIntegerField(blank=True, null=True)),
                ('stores', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_sales_estimate',
                'indexes': [models.Index(fields=['yyq', 'trdar_cd'], name='analytics_s_yyq_bea641_idx'), models.Index(fields=['svc_induty_cd'], name='analytics_s_svc_ind_893f5d_idx')],
            },
        ),
    ]
