# Generated by Django 5.2.5 on 2025-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_salesestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRadiusStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trdar_cd', models.CharField(db_index=True, max_length=10)),
                ('trdar_cd_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('signgu_cd', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('adstrd_cd', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('radius', models.IntegerField(db_index=True, default=2000)),
                ('total', models.IntegerField(default=0)),
                ('counts_lcls', models.JSONField(blank=True, default=dict)),
                ('counts_mcls', models.JSONField(blank=True, default=dict)),
                ('counts_scls', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('raw_meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_store_radius_stat',
                'unique_together': {('trdar_cd', 'radius')},
            },
        ),
        migrations.DeleteModel(
            name='SalesEstimate',
        ),
    ]
