# Generated by Django 5.2.5 on 2025-08-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_storeradiusstat_delete_salesestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trdar_cd', models.CharField(db_index=True, max_length=10)),
                ('radius', models.IntegerField(default=2000)),
                ('total', models.IntegerField(default=0)),
                ('cx', models.FloatField(blank=True, null=True)),
                ('cy', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_store_count',
                'unique_together': {('trdar_cd', 'radius')},
            },
        ),
    ]
