# Generated by Django 5.2.5 on 2025-08-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_storecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecount',
            name='counts_lcls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storecount',
            name='counts_mcls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storecount',
            name='counts_scls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='storecount',
            index=models.Index(fields=['trdar_cd', 'radius'], name='analytics_s_trdar_c_41d424_idx'),
        ),
    ]
